### ISSUE TITLE
[todo]following api频率限制过低的解决方法

### ISSUE THREAD

**Issue by ion-ponyai** [ionic-bond/twitter-monitor#6]
目前整个monitor的瓶颈是following，每个token每分钟只能查询一次
有一个想法是：正常情况下只查询user信息，user里的following number变了再去查following

**Comment by ionic-bond** [comment]
https://github.com/ionic-bond/twitter-monitor/commit/cee4f0029ec99adb3da84e5544de87f61a3784a3

**Comment by ionic-bond** [comment]
https://github.com/ionic-bond/twitter-monitor/commit/cee4f0029ec99adb3da84e5544de87f61a3784a3
